### PR TITLE
Allocate status bar buffer based on sbar height

### LINKED ISSUE #71: Thatcher's Techbase 4x/8x resolution crash
While playing Thatcher's Techbase(original or arcade), a boom compatible wad, changing the resolution to 4x or 8x consistently produces a crash right when selecting the option. All other settings are default. I've tried a couple other boom compatible wads and all seem to work fine with no crashes.

I'm not sure if this is just the wad being a problem or it's on Nugget's end.

### PR DESCRIPTION
**Pull request by ceski-1**
Fixes https://github.com/MrAlaux/Nugget-Doom/issues/71

### CODE REVIEW

**Comment by ceski-1** [comment]
@MrAlaux When you update the changelog, please credit Fabian for the solution.

**Comment by MrAlaux** [comment]
> @MrAlaux When you update the changelog, please credit Fabian for the solution.

Would you mind if I credit you too? You did make the PR after all.

**Comment by ceski-1** [comment]
> Would you mind if I credit you too? You did make the PR after all.

Sure, no problem.

**Comment by MrAlaux** [comment]
The warnings are emitted every time the screen is restarted, I think that's unnecessary. Could you add something along the lines of `static boolean firsttime` to `ST_loadGraphics()` to only print them once?
Woof is affected too, but maybe Fabian does want to keep the multiple warnings.

Unrelated: excuse me @fabiangreffrath, the following weird characters are printed alongside the warnings:
imagen
I remember seeing some relevant commits regarding that output, but I don't remember the details and if this is expected. Mind the antique window style, that's actually Win7.

**Comment by ceski-1** [comment]
> The warnings are emitted every time the screen is restarted, I think that's unnecessary.

I agree, they only show once now.

**Comment by MrAlaux** [comment]
Alright, looks good to me. Anything left you can think of?

**Comment by ceski-1** [comment]
I'm happy with this but maybe wait for the upstream PR in case there are more changes.

**Comment by fabiangreffrath** [comment]
> Unrelated: excuse me @fabiangreffrath, the following weird characters are printed alongside the warnings:

This means that this code doesn't work on your system. @rfomin any ideas?

https://github.com/fabiangreffrath/woof/blob/54eb621036c0e5b9abe57fec8aad2eb3f3908367/src/i_printf.c#L63-L83

**Comment by rfomin** [comment]
> > Unrelated: excuse me @fabiangreffrath, the following weird characters are printed alongside the warnings:
> 
> This means that this code doesn't work on your system. @rfomin any ideas?
> 
> https://github.com/fabiangreffrath/woof/blob/54eb621036c0e5b9abe57fec8aad2eb3f3908367/src/i_printf.c#L63-L83

It seems `ENABLE_VIRTUAL_TERMINAL_PROCESSING` works only on Windows 10+. I will try to fix this.

**Comment by rfomin** [comment]
@MrAlaux could you please test this commit https://github.com/fabiangreffrath/woof/commit/3c546497117231910fccba0979a18640f4e64df3 ? Error messages should appear in the console without extra characters.

**Comment by MrAlaux** [comment]
> @MrAlaux could you please test this commit [fabiangreffrath@3c54649](https://github.com/fabiangreffrath/woof/commit/3c546497117231910fccba0979a18640f4e64df3) ? Error messages should appear in the console without extra characters.

Yep, seems to be working. See:

<details>
  <summary>Before</summary>
  
imagen
</details>

<details>
  <summary>After</summary>
  
imagen
</details>

**Comment by fabiangreffrath** [comment]
Thank you @rfomin!

**Pull request merged**
